server:
  port: 8801

spring:
  application:
    name: spring-cloud-config-client
  cloud:
      bus:
        enabled: true
        trace:
          enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
